
/* Drop Tables */

DROP TABLE ADMIN_NOTICES CASCADE CONSTRAINTS;
DROP TABLE CARTS CASCADE CONSTRAINTS;
DROP TABLE ITEM_IMAGES CASCADE CONSTRAINTS;
DROP TABLE ORDERDETAILS CASCADE CONSTRAINTS;
DROP TABLE REVIEWS CASCADE CONSTRAINTS;
DROP TABLE OPTIONS CASCADE CONSTRAINTS;
DROP TABLE ITEMS CASCADE CONSTRAINTS;
DROP TABLE CATEGORYS CASCADE CONSTRAINTS;
DROP TABLE ITEM_QUESTIONS CASCADE CONSTRAINTS;
DROP TABLE ORDERS CASCADE CONSTRAINTS;
DROP TABLE USER_LOGIN_LOGS CASCADE CONSTRAINTS;
DROP TABLE USERS CASCADE CONSTRAINTS;
DROP TABLE USER_QUESTIONS CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE ADMIN_NOTICES
(
	NOTICE_NO number NOT NULL,
	NOTICE_TITLE varchar2(100) NOT NULL,
	NOTICE_CONTENTS varchar2(1000) NOT NULL,
	NOTICE_IMPORTANT char DEFAULT 'Y',
	NOTICE_PASSWORD varchar2(20) NOT NULL,
	NOTICE_CREATE_DATE date DEFAULT SYSDATE,
	USER_NO number NOT NULL,
	PRIMARY KEY (NOTICE_NO)
);


CREATE TABLE CARTS
(
	CART_NO number NOT NULL,
	USER_NO number NOT NULL,
	OPT_NO number NOT NULL,
	CART_IMAGE varchar2(1000) NOT NULL,
	CART_TOTALPRICE number NOT NULL,
	CART_COUNT number DEFAULT 1,
	PRIMARY KEY (CART_NO)
);


CREATE TABLE CATEGORYS
(
	CATE_NO number NOT NULL,
	CATE_CONTENTS varchar2(300) NOT NULL,
	CATE_SUB_NO number,
	PRIMARY KEY (CATE_NO)
);


CREATE TABLE ITEMS
(
	ITEM_NO number NOT NULL,
	ITEM_NAME varchar2(100) NOT NULL,
	ITEM_CONTENTS varchar2(500) NOT NULL,
	ITEM_PRICE number NOT NULL,
	ITEM_DISPLAY_AVAILABLE char DEFAULT 'Y',
	ITEM_SELL_AVAILABLE char DEFAULT 'Y',
	ITEM_CURRENT_DISCOUNT number,
	ITEM_CREATE_DATE date DEFAULT SYSDATE,
	CATE_NO number NOT NULL,
	PRIMARY KEY (ITEM_NO)
);


CREATE TABLE ITEM_IMAGES
(
	ITEM_NO number NOT NULL,
	ITEM_IMAGES_IMAGE varchar2(1000) NOT NULL
);


CREATE TABLE ITEM_QUESTIONS
(
	ITEM_QUESTION_NO number NOT NULL,
	ITEM_QUESTION_TITLE varchar2(100) NOT NULL,
	ITEM_QUESTION_CONTENTS varchar2(500) NOT NULL,
	ITEM_QUESTION_FILENAME varchar2(1000),
	ITEM_QUESTION_PASSWORD varchar2(20) NOT NULL,
	ITEM_QUESTION_SECRET char DEFAULT 'S',
	USER_NO number NOT NULL,
	ITEM_QUESTION_AVAILABLE char DEFAULT 'Y',
	ITEM_QUESTION_CREATE_DATE date DEFAULT SYSDATE,
	PRIMARY KEY (ITEM_QUESTION_NO)
);


CREATE TABLE OPTIONS
(
	OPT_NO number NOT NULL,
	OPT_COLOR varchar2(20) NOT NULL,
	OPT_SIZE varchar2(10) NOT NULL,
	OPT_STOCK number DEFAULT 0 NOT NULL,
	OPT_CURRENT_PRICE number NOT NULL,
	OPT_SELL_AVAILABLE char DEFAULT 'Y',
	ITEM_NO number NOT NULL,
	PRIMARY KEY (OPT_NO)
);


CREATE TABLE ORDERDETAILS
(
	ORDER_ITEM_NO number NOT NULL,
	ORDER_QTY number NOT NULL,
	ORDER_NO number NOT NULL,
	OPT_NO number NOT NULL,
	PRIMARY KEY (ORDER_ITEM_NO)
);


CREATE TABLE ORDERS
(
	ORDER_NO number NOT NULL,
	ORDER_CREATE_DATE date DEFAULT SYSDATE,
	ORDER_STATE varchar2(10) NOT NULL,
	USER_NO number NOT NULL,
	PRIMARY KEY (ORDER_NO)
);


CREATE TABLE REVIEWS
(
	REVIEW_NO number NOT NULL,
	REVIEW_CONTENTS varchar2(1000) NOT NULL,
	REVIEW_PHOTO varchar2(1000) NOT NULL,
	REVIEW_COUNTS number DEFAULT 0 NOT NULL,
	REVIEW_CREATE_DATE date DEFAULT SYSDATE,
	REVIEW_SCORE number(3,1) NOT NULL,
	USER_NO number NOT NULL,
	OPT_NO number NOT NULL,
	PRIMARY KEY (REVIEW_NO)
);


CREATE TABLE USERS
(
	USER_NO number NOT NULL,
	USER_ID varchar2(10) NOT NULL,
	USER_PASSWORD varchar2(20) NOT NULL,
	USER_NAME varchar2(50) NOT NULL,
	USER_GENDER char DEFAULT 'M' NOT NULL,
	USER_BIRTHDAY varchar2(10) NOT NULL,
	QUESTION_NO number NOT NULL,
	USER_ANSWER varchar2(100) NOT NULL,
	USER_ADDRESS1 varchar2(50) NOT NULL,
	USER_ADDRESS2 varchar2(50) NOT NULL,
	USER_TEL varchar2(10),
	USER_PHONE varchar2(10) NOT NULL,
	USER_SNS_CHECKED char(1) DEFAULT 'N',
	USER_EMAIL varchar2(20) NOT NULL,
	USER_EMAIL_CHECKED char(1) DEFAULT 'N',
	USER_FOREVER char(1) DEFAULT 'N',
	USER_AVAILABLE char DEFAULT 'Y',
	USER_CREATE_DATE date DEFAULT SYSDATE,
	PRIMARY KEY (USER_NO)
);


CREATE TABLE USER_LOGIN_LOGS
(
	LOGIN_IP varchar2(20),
	USER_NO number NOT NULL,
	USER_LOGIN_CREATE_DATE date DEFAULT SYSDATE
);


CREATE TABLE USER_QUESTIONS
(
	QUESTION_NO number NOT NULL,
	QUESTION_TEXT varchar2(200),
	PRIMARY KEY (QUESTION_NO)
);



/* Create Foreign Keys */

ALTER TABLE ITEMS
	ADD FOREIGN KEY (CATE_NO)
	REFERENCES CATEGORYS (CATE_NO)
;


ALTER TABLE ITEM_IMAGES
	ADD FOREIGN KEY (ITEM_NO)
	REFERENCES ITEMS (ITEM_NO)
;


ALTER TABLE OPTIONS
	ADD FOREIGN KEY (ITEM_NO)
	REFERENCES ITEMS (ITEM_NO)
;


ALTER TABLE CARTS
	ADD FOREIGN KEY (OPT_NO)
	REFERENCES OPTIONS (OPT_NO)
;


ALTER TABLE ORDERDETAILS
	ADD FOREIGN KEY (OPT_NO)
	REFERENCES OPTIONS (OPT_NO)
;


ALTER TABLE REVIEWS
	ADD FOREIGN KEY (OPT_NO)
	REFERENCES OPTIONS (OPT_NO)
;


ALTER TABLE ORDERDETAILS
	ADD FOREIGN KEY (ORDER_NO)
	REFERENCES ORDERS (ORDER_NO)
;


ALTER TABLE ADMIN_NOTICES
	ADD FOREIGN KEY (USER_NO)
	REFERENCES USERS (USER_NO)
;


ALTER TABLE CARTS
	ADD FOREIGN KEY (USER_NO)
	REFERENCES USERS (USER_NO)
;


ALTER TABLE ITEM_QUESTIONS
	ADD FOREIGN KEY (USER_NO)
	REFERENCES USERS (USER_NO)
;


ALTER TABLE ORDERS
	ADD FOREIGN KEY (USER_NO)
	REFERENCES USERS (USER_NO)
;


ALTER TABLE REVIEWS
	ADD FOREIGN KEY (USER_NO)
	REFERENCES USERS (USER_NO)
;


ALTER TABLE USER_LOGIN_LOGS
	ADD FOREIGN KEY (USER_NO)
	REFERENCES USERS (USER_NO)
;


ALTER TABLE USERS
	ADD FOREIGN KEY (QUESTION_NO)
	REFERENCES USER_QUESTIONS (QUESTION_NO)
;



